{{ define ".boto" }}
[Credentials]

gs_service_key_file = /backup/serviceaccount.json

[Boto]

https_validate_certificates = True

[GSUtil]

default_nguage = en
api_version = 2
default_project_id = {{ .Values.gcs.projectId }}

{{ end }}
{{- if .Values.gcs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-gcs
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  .boto: |
    {{ include ".boto" . | b64enc }}
  serviceaccount.json: |
    {{ .Values.gcs.serviceAccountKey }}
{{- end }}
